CREATE SCHEMA DEVOIR;

CREATE TABLE DEVOIR.BUREAUX
(
	BUREAU_ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL UNIQUE,
	BATIMENT  CHAR CHECK (BATIMENT IN ('A', 'B')),
	ETAGE     INTEGER CHECK (ETAGE IN (1, 2)),
	NUMERO    INTEGER CHECK ( NUMERO > 99 AND NUMERO < 1000),
	LIMITE    INTEGER,

	CONSTRAINT PK_BUREAUX PRIMARY KEY (BATIMENT, ETAGE, NUMERO)
);

CREATE TABLE DEVOIR.EQUIPE
(
	EQUIPE_ID VARCHAR(10), 
	
	CONSTRAINT PK_EQUIPE PRIMARY KEY (EQUIPE_ID)
);


CREATE TABLE DEVOIR.PERSONNES
(
	PERSONNE_ID INTEGER GENERATED ALWAYS AS IDENTITY,
	NOM         VARCHAR(25),
	PRENOM      VARCHAR(25),
	BUREAU      INTEGER,
	MAIL        VARCHAR(50),
	EQUIPE      VARCHAR(10),
	
	CONSTRAINT PK_PERSONNES PRIMARY KEY (PERSONNE_ID),
	CONSTRAINT FK_PERSONNES_BUREAUX FOREIGN KEY (BUREAU) REFERENCES DEVOIR.BUREAUX(BUREAU_ID),
	CONSTRAINT FK_BUREAUX_EQUIPE FOREIGN KEY (EQUIPE) REFERENCES DEVOIR.EQUIPE(EQUIPE_ID)
);

CREATE TABLE DEVOIR.RESPONSABLE
(
	PERSONNE     INTEGER,
	IDENTIFIANT  VARCHAR(20),
	MOT_DE_PASSE VARCHAR(20),

	CONSTRAINT PK_RESPONSABLE PRIMARY KEY (IDENTIFIANT),
	CONSTRAINT FK_RESPONSABLE_PERSONNES FOREIGN KEY (PERSONNE) REFERENCES DEVOIR.PERSONNES(PERSONNE_ID)
);

CREATE TABLE DEVOIR.MESSAGE
(
	MESSAGE_ID   INTEGER GENERATED ALWAYS AS IDENTITY,
	MESSAGE      VARCHAR(2000),
	ETAT         BOOLEAN,
	AUTEUR       INTEGER,
	
	CONSTRAINT PK_MESSAGE PRIMARY KEY (MESSAGE_ID),
	CONSTRAINT FK_MESSAGE_PERSONNES FOREIGN KEY (AUTEUR) REFERENCES DEVOIR.PERSONNES(PERSONNE_ID)
);



DROP TABLE DEVOIR.MESSAGE;
DROP TABLE DEVOIR.RESPONSABLE;
DROP TABLE DEVOIR.PERSONNES;
DROP TABLE DEVOIR.EQUIPE;
DROP TABLE DEVOIR.BUREAUX;


