all:
	javac fr/jonesalexis/project/pdj/*.java 
	javac fr/jonesalexis/project/pdj/httpserver/*.java
	javac fr/jonesalexis/project/pdj/proto/piz/*.java
	javac fr/jonesalexis/project/pdj/xml/*.java
	
start:
	java fr/jonesalexis/project/pdj/Main
client:
	java fr/jonesalexis/project/pdj/ClientExample

	
clean:
	rm -f fr/jonesalexis/project/pdj/*.class 
	rm -f fr/jonesalexis/project/pdj/httpserver/*.class
	rm -f fr/jonesalexis/project/pdj/piz/*.class
	rm -f fr/jonesalexis/project/pdj/xml/*.class
